### PR TITLE
fix(frontend): improve source ui on mobile for contibutions

### LINKED ISSUE #3300: Ajout de la source de la fiche dans certaines contributions
# Problème

On a eu une réunion avec des personnes de Service-Public.fr, nous leur avons présenté les contributions notamment et on a remarqué une chose : lorsqu'on reprend entièrement la fiche Service-Public.fr on n'indique pas la source... :O
(on avait un peu honte de leur montrer cela...)

Exemple d'une contribution ici : https://cdtn-preprod-code-travail.dev2.fabrique.social.gouv.fr/contribution/a-quelles-indemnites-peut-pretendre-un-salarie-qui-part-a-la-retraite

# Solution 

Serait-il possible de rajouter la source de la fiche utilisée lorsqu'on utilise une fiche en entière (comme cela est traitée dans nos autre contenus) 

Exemple de visuel 
image

### PR DESCRIPTION
**Pull request by lionelB**
fancy ui
- remove dash between source and date on mobile
- move source and date on separate line on mobile
closes #3300

### CODE REVIEW

File: packages/code-du-travail-frontend/src/contributions/Contribution.js [hunk 1]
```diff
@@ -179,9 +179,11 @@ const Contribution = ({ answers, content }) => {
                   >
                     Fiche {getLabelBySource(content.source)}
                   </a>
-                </>
+                </span>
+              )}
+              {content.source && content.date && (
```
Comment (m-maillot) [inline packages/code-du-travail-frontend/src/contributions/Contribution.js]: I don't understand the condition `content.source` here. Should be `content.url` as tested line 172?

**Review by m-maillot — APPROVED** [review]
:+1:
