### PR TITLE
fix(RGAA 10.6): make the email link more visible in contact dialog

### LINKED ISSUE #4012: [AUDIT RGAA] P-all - 10.6
Sur la grille est indiqué :
_Modale via le bouton « contact » en bas de page : un lien n’est pas visible par rapport a son texte adjacent → changer la couleur du lien pour le rendre visible par rapport au texte a coté_

C'était comme ça :
Screenshot 2021-11-15 at 16 30 45

Je l'ai mis comme ça (comme tous nos liens) :
Screenshot 2021-11-15 at 16 31 11

### PR DESCRIPTION
**Pull request by carolineBda**
Fix #4012

### CODE REVIEW

**Review by m-maillot — APPROVED** [review]

File: packages/code-du-travail-frontend/src/common/ContactModal.js [hunk 1]
```diff
@@ -47,9 +48,9 @@ export const ContactModal = ({ children: renderProp }) => {
               ce site ou si vous avez rencontré un{" "}
               <strong>problème technique</strong>, vous pouvez nous contacter à
               cette adresse&nbsp;:{" "}
-              <StyledLink href="mailto:codedutravailnumerique@travail.gouv.fr">
+              <Link href="mailto:codedutravailnumerique@travail.gouv.fr">
```
Comment (maxgfr) [inline packages/code-du-travail-frontend/src/common/ContactModal.js:51]: 👍

**Review by maxgfr — APPROVED** [review]
