### PR TITLE
fix(themes): use themes from dataset

### LINKED ISSUE #192: wording thèmes
1) Navigation par thèmes: 
a) wording.
- titres: les titres sont à revoir : 
-sous titres: On ne peut pas mettre en ligne avec les sous titres actuels. le wording est à faire.

-proposition:
*  embauche et exécution du contrat de travail ou  contrat de travail et embauche
             
               sous titre proposition: obligations liés à l'embauche

  * Rupture du contrat de travail: 
                                 sous titre proposition : Licenciement, démission, rupture conventionnelle...
=> (contrat de travail, pas contrat simple)
* Rémunération:
                sous titre proposition: Salaire, primes, avantages, bulletin de salaire
* Santé et sécurité au travail: 
      
              sous titre proposition : conditions de travail, surveillance médicale, pénibilité
* Durée du travail et congés:
   
               sous titre proposition: heures supplémentaires, congés payés, durée maximale du travail
* maladie et inaptitudes: maladie et inaptitude.

                  sous titre proposition : l'inaptitude, procédure, contentieux, arrêts de travail...
*Formation: à supprimer  ( pas nécessaire pour le moment pour l'outil)
*Dialogue social: ( suppression possible. dans quelques sprints)

                   sous titre proposition : représentants du personnel et négociation

* proposition de thème : contentieux et coercitif
                   
                   sous titre proposition: prud’hommes, la prescription, volet pénal, l'inspection du travail

### PR DESCRIPTION
**Pull request by lionelB**
fix #192

### CODE REVIEW

File: packages/code-du-travail-frontend/pages/theme.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ import parents from "unist-util-parents";
 import { Link, Router } from "../routes";
 import Search, { SearchQuery } from "../src/search/Search";
 import Categories from "../src/Categories";
-import themes from "../src/data/themes.json";
+import themes from "../../code-du-travail-data/dataset/themes-front.json";
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/pages/theme.js]: :warning: This is kind of dangerous :warning: 
In a monorepo environment you should go through parent hierarchy *in the source code*!
The sources shouldn't be aware of the monorepo environment.
If you need to access to another package, use the created symlinks 

```diff
-import themes from "../../code-du-travail-data/dataset/themes-front.json";
+import themes from "@cdt/data/dataset/themes-front.json";
```

File: packages/code-du-travail-frontend/src/Categories.js [hunk 2]
```diff
@@ -3,7 +3,7 @@ import { Link } from "../routes";
 
 import { Container, Categories } from "@cdt/ui";
 
-import themes from "./data/themes.json";
+import themes from "../../code-du-travail-data/dataset/themes-front.json";
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/Categories.js]: :warning: This is kind of dangerous :warning: 
In a monorepo environment you should go through parent hierarchy *in the source code*!
The sources shouldn't be aware of the monorepo environment.
If you need to access to another package, use the created symlinks 

```diff
-import themes from "../../code-du-travail-data/dataset/themes-front.json";
+import themes from "@cdt/data/dataset/themes-front.json";
```

**Review by douglasduteil — CHANGES_REQUESTED** [review]

File: packages/code-du-travail-frontend/src/data/themes-front.json [hunk 3]
```diff
@@ -0,0 +1 @@
+../../../code-du-travail-data/dataset/themes-front.json
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/data/themes-front.json]: Hum... 
That will work but why not using the file from the node_modules ?

```
@cdt/data/dataset/themes-front.json
```

Comment (lionelB) [reply packages/code-du-travail-frontend/src/data/themes-front.json]: didn't know we can do that since I touhg data doesn't export any thing but It works 
thanks !

**Review by douglasduteil — APPROVED** [review]
