### PR TITLE
fix(accessibility): some typos and use accessibilite for the link

### LINKED ISSUE #3351: [ui] safari tooltips
Il semblerait que les tooltips aient un petit souci de CSS sur Safari :

Initial : 

Capture d’écran 2021-03-13 à 12 28 49

Over :

Capture d’écran 2021-03-13 à 12 28 56

After :

Capture d’écran 2021-03-13 à 12 29 01

### PR DESCRIPTION
**Pull request by m-maillot**
Closes #3351

Finally, find it! \o/

### CODE REVIEW

File: packages/code-du-travail-frontend/src/web-components/tooltip.js [hunk 1]
```diff
@@ -58,14 +59,14 @@ class WebComponentsTooltip extends LitElement {
...
-      .tooltip .content.visible {
+      .content.visible {
         display: block;
       }
     `;
   }
 
   render() {
-    return html`<div
+    return html` <div
```
Comment (lionelB) [inline packages/code-du-travail-frontend/src/web-components/tooltip.js:69]:
```suggestion
    return html`<div
```

Comment (m-maillot) [reply packages/code-du-travail-frontend/src/web-components/tooltip.js:69]: It's automated formatted by prettier. Should we change the prettier rules?

Comment (lionelB) [reply packages/code-du-travail-frontend/src/web-components/tooltip.js:69]: ok, I was not sure it was intentionnal. we leave it like that

**Review by lionelB — APPROVED** [review]
