### PR TITLE
Lionelb/fix modal ccn

### LINKED ISSUE #208: [bug] modal recherche ccn: résultats
Par contre : la recherche " boulangerie industrielle est déceptive": le premier résultat n'est pas la boulangerie, le surlignement ne fait pas apparaître en premier la bonne convention collective.

Dans le moteur principal, il n'y a pas de soucis avec ce test.

### PR DESCRIPTION
**Pull request by lionelB**
fix #208

### CODE REVIEW

File: packages/code-du-travail-data/dataset/kali/utils.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+async function batchPromise(list, size, callback, progress) {
+  let results = [];
+  for (items of batch(list, size)) {
+    let values = await Promise.all(items.map(callback));
+    results = results.concat(...values);
```
Comment (douglasduteil) [inline packages/code-du-travail-data/dataset/kali/utils.js]: same as `results = [...results, ...values]`

File: packages/code-du-travail-data/dataset/kali/utils.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
+async function batchPromise(list, size, callback, progress) {
+  let results = [];
+  for (items of batch(list, size)) {
+    let values = await Promise.all(items.map(callback));
```
Comment (douglasduteil) [inline packages/code-du-travail-data/dataset/kali/utils.js]: here `values` is a const right ?

File: packages/code-du-travail-data/dataset/kali/yarn.lock [hunk 3]
```diff
@@ -0,0 +1,918 @@
+# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
```
Comment (douglasduteil) [inline packages/code-du-travail-data/dataset/kali/yarn.lock]: this packages is not part of the monorepo ??

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+      className: "full-width"
+    };
+
+    return (
+      <form>
+        <h2>Convention collective</h2>
+        <div>
+          Saisissez l&apos;identifiant de convention collective (IDCC), le nom
+          de la branche, ou le code NAF :
+          <div style={{ marginTop: 10 }}>
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 5]
```diff
@@ -0,0 +1,188 @@
...
+                onSuggestionsClearRequested={this.onSuggestionsClearRequested}
+                onSuggestionSelected={this.onSuggestionSelected}
+                getSuggestionValue={getSuggestionValue}
+                renderSuggestion={renderSuggestion}
+                renderSuggestionsContainer={renderSuggestionsContainer}
+                inputProps={inputProps}
+                theme={suggesterTheme}
+              />
+            ) : (
+              <div>
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: why you need a div here ?

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 6]
```diff
@@ -0,0 +1,188 @@
...
+                <X
+                  size="16"
+                  onClick={this.onSelectionCleared}
+                  style={{ marginLeft: 5, cursor: "pointer" }}
+                />
+              </div>
+            )}
+          </div>
+          <div>
+            <div style={{ marginTop: 20, fontWeight: "bold" }}>
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 7]
```diff
@@ -0,0 +1,188 @@
...
+                inputProps={inputProps}
+                theme={suggesterTheme}
+              />
+            ) : (
+              <div>
+                <ConventionPreview data={this.state.selected} />
+                <X
+                  size="16"
+                  onClick={this.onSelectionCleared}
+                  style={{ marginLeft: 5, cursor: "pointer" }}
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+            </div>
+            <li>
+              Elle doit figurer au <b>bulletin de paie</b>, et sur une notice
+              remise à l&apos;embauche ou <b>sur le contrat de travail</b>
+            </li>
+            <li>
+              Sur l&apos;affichage obligatoire dans l&apos;entreprise (avec les
+              modalités de consultation en entreprise)
+            </li>
+            <div style={{ marginTop: 20, fontWeight: "bold" }}>
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+              En principe celle relevant de l&apos;activité principale dans
+              l&apos;entreprise pour les cas les plus simples.
+            </li>
+          </div>
+        </div>
+      </form>
+    );
+  }
+}
+export { ConventionForm };
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: Might want to put this line 8 as :

```diff
-class ConventionForm extends React.Component {
+export class ConventionForm extends React.Component {
````

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+    ? `${suggestion._source.idcc} - ${suggestion._source.title}`
+    : suggestion._source.title;
+
+const ConventionPreview = ({ data }) => (
+  <a target="_blank" href={data.url} rel="noopener noreferrer">
+    <Download
+      alt="Télécharger la convention"
+      title="Télécharger la convention"
+      size="16"
+      style={{ marginRight: 5 }}
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

File: packages/code-du-travail-frontend/src/common/ConventionForm.js [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+  whitespace: nowrap;
+  textoverflow: ellipsis;
+  width: 90%;
+  overflow: hidden;
+  padding: 5px;
+`;
+const renderSuggestion = suggestion => {
+  return (
+    <Suggestion>
+      <Button link style={{ whiteSpace: "normal", fontSize: ".9rem" }}>
```
Comment (douglasduteil) [inline packages/code-du-travail-frontend/src/common/ConventionForm.js]: prefer use of styled-components or atomic classes

**Review by douglasduteil — CHANGES_REQUESTED** [review]
What a Pyramid of DOOM BTW

- We shouldn't mix data layer and front request in the same files...
- We shouldn't try catch the whole functions... as Express, [Koa has an global error handler](https://github.com/koajs/koa/wiki/Error-Handling)
- `packages/code-du-travail-frontend/src/common/ConventionForm.js` looks like a good example of a Smart component in need of using lower abstractions

File: packages/code-du-travail-frontend/src/common/ConventionForm.js (hunk 5 above)
Comment (lionelB) [reply packages/code-du-travail-frontend/src/common/ConventionForm.js]: because there is 2 child so i need a wrapper ? what do you suggest ?

File: packages/code-du-travail-frontend/src/common/ConventionForm.js (hunk 9 above)
Comment (lionelB) [reply packages/code-du-travail-frontend/src/common/ConventionForm.js]: Is there a difference ?

File: packages/code-du-travail-frontend/src/common/ConventionForm.js (hunk 5 above)
Comment (douglasduteil) [reply packages/code-du-travail-frontend/src/common/ConventionForm.js]: Does a React fragment works in that case ?

File: packages/code-du-travail-frontend/src/common/ConventionForm.js (hunk 9 above)
Comment (douglasduteil) [reply packages/code-du-travail-frontend/src/common/ConventionForm.js]: The end result is the same.
IMO the code is more expectable as you can read what is exported next to the export statement but it's a taste.

File: packages/code-du-travail-frontend/src/common/ConventionForm.js (hunk 5 above)
Comment (lionelB) [reply packages/code-du-travail-frontend/src/common/ConventionForm.js]: yep

**Comment by lionelB** [comment]
chad-dance

File: packages/code-du-travail-api/src/server/routes/api.js [hunk 12]
```diff
@@ -31,7 +30,7 @@ router.get(`${BASE_URL}/search`, async ctx => {
 
     ctx.body = await codeDuTravailNumerique.search({ query, mustNot });
   } catch (error) {
-    logger.error(error);
+    ctx.throw(error);
```
Comment (douglasduteil) [inline packages/code-du-travail-api/src/server/routes/api.js]: Do we still need to "try catch" ?
a "natural" throw would work right ?

**Review by douglasduteil — CHANGES_REQUESTED** [review]

File: packages/code-du-travail-api/src/server/routes/api.js (hunk 12 above)
Comment (lionelB) [reply packages/code-du-travail-api/src/server/routes/api.js]: you mean because `codeDuTravailNumerique.search()` already throw ans error ?

**Review by douglasduteil — APPROVED** [review]

File: packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js [hunk 13]
```diff
@@ -121,17 +124,14 @@ async function search({
           "all_text.french_exact": {},
           "all_text.shingle": {},
           "path.french_stemmed": {},
-          "path.french_exact": {}
+          "path.french_exact": {},
+          ...fieldHightlight
```
Comment (revolunet) [inline packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js:128]: typo

File: packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js [hunk 14]
```diff
@@ -16,7 +16,9 @@ async function search({
   size = 10,
   must = [],
   mustNot = [],
+  filter = [],
   should = [],
+  fieldHightlight = [],
```
Comment (revolunet) [inline packages/code-du-travail-api/src/server/data_sources/code_du_travail_numerique.js:21]: typo

File: packages/code-du-travail-data/dataset/kali/utils.js [hunk 15]
```diff
@@ -0,0 +1,27 @@
...
+  return Array.from({ length: Math.ceil((end - start) / size) }).map(
+    (_, i) => i * size
+  );
+}
+
+module.exports = {
+  range,
+  batch,
+  batchPromise
+};
```
Comment (revolunet) [inline packages/code-du-travail-data/dataset/kali/utils.js:27]: C'est mignon et mérite quelques TU :)

Comment (lionelB) [reply packages/code-du-travail-data/dataset/kali/utils.js:27]: mignon !??!!?  mais oui on pourrait ajouter quelques tests sur ces fonctions
