### PR TITLE
fix(widget): track widget click

### LINKED ISSUE #5074: Regarder comment tracker les widgets sans impacter nos stats  : ce ne sont pas de nouvelle visites
- Pour le widget search : compter une visite seulement quand l'usager a lancé une recherche depuis le widget (et qu'il a donc ouvert un onglet CDTN)
- Pour les simulateurs : compter une visite lorsque l'usager a cliqué sur "Commencer"
- On veut connaître les sites depuis lesquels les visites arrievnt pour chaque widget
- Régler le problème de cookies dans l'iframe

### PR DESCRIPTION
**Pull request by carolineBda**
Fix [#5074](https://github.com/SocialGouv/code-du-travail-numerique/issues/5074)

### CODE REVIEW

File: packages/code-du-travail-frontend/pages/_app.tsx [hunk 1]
```diff
@@ -55,6 +49,7 @@ function MyApp({ Component, pageProps }: AppProps) {
           push(["setReferrerUrl", referrerUrl]);
         }
       },
+      excludeUrlsPatterns: [/\/widgets\/.*/],
```
Comment (maxgfr) [inline packages/code-du-travail-frontend/pages/_app.tsx]: top 🔥

**Review by maxgfr — APPROVED** [review]

**Review by Viczei — APPROVED** [review]

**Review by maxgfr — APPROVED** [review]

**Review by m-maillot — APPROVED** [review]
