### PR TITLE
fix(annuaire): add feedback from last GT meeting

### LINKED ISSUE #464: [ GT suites] Suggestions: amélioratoin annuaire
1)	Annuaires :
-	[x] CICAS: questions retraite complémentaire. Wording à ajouter.
-	[x] Ajouter le lien dans les numéros de téléphone : renvoi vers interface type Google Map ?
-	[x] Chambres consulaires : à faire descendre dans les propositions d'annuaires
-	[x] Ajouter de nouveaux contacts : comme les Maisons de la justice et du droit
-	[ ] L’utilisateur cherche à cliquer sur la tuile et attend une action (renvoi direct vers le contact, affichage détails ?)-->UX/SPEC, dev in 1.10?

### PR DESCRIPTION
**Pull request by lionelB**
fix #464 
- add a subtitle for cicas document
- address link to OSM map
- phone number link to "tel:"
- add mjd documents
- set document order (based on boost)

### CODE REVIEW

File: packages/code-du-travail-frontend/src/search/AddressResults.js [hunk 1]
```diff
@@ -84,15 +90,22 @@ function AddressCard({ data }) {
   return (
     <Card>
       <CardTitle>{data.title}</CardTitle>
-      <CardAddress>
+      {data.subtitle && <CardSubtitle>{data.subtitle}</CardSubtitle>}
+      <CardAddress
```
Comment (revolunet) [inline packages/code-du-travail-frontend/src/search/AddressResults.js:94]: maybe ensure we have some lat/lon before rendering `CardAddress` ?

**Review by revolunet — APPROVED** [review]

**Review by douglasduteil — APPROVED** [review]

File: packages/code-du-travail-frontend/src/search/AddressResults.js (hunk 1 above)
Comment (lionelB) [reply packages/code-du-travail-frontend/src/search/AddressResults.js:94]: @revolunet since we retrieve data from annuaire, I'm pretty confident that address exist
also if there is no coord, indexing will break
