### PR TITLE
fix(contributions): rm trailing 0 when no answer references fix #1777 

### LINKED ISSUE #1777: [typo] fix trailing 0 in UI
Image collée à 2019-11-21 10-29

cc @June-law

### PR DESCRIPTION
**Pull request by revolunet**
fix #1777

### CODE REVIEW

File: packages/code-du-travail-frontend/src/contributions/Contribution.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ const References = ({ references }) => {
 
   return (
     <React.Fragment>
-      {references && references.length && (
+      {references && references.length !== 0 && (
```
Comment (nkrmr) [inline packages/code-du-travail-frontend/src/contributions/Contribution.js:56]: Not better to do references.length > 0 ?

Comment (UnbearableBear) [reply packages/code-du-travail-frontend/src/contributions/Contribution.js:56]: Same I'd say :)

**Review by UnbearableBear — APPROVED** [review]

**Review by nkrmr — APPROVED** [review]
